// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ameato/controller"
	"ameato/db"
	"ameato/handler"
	"ameato/repository"
	"ameato/router"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeRouter() *gin.Engine {
	gormDB := db.InitDB()
	getMessageRepository := repository.NewGetMessageRepository(gormDB)
	getController := controller.NewGetController(getMessageRepository)
	getHandler := handler.NewGetHandler(getController)
	createMessageRepository := repository.NewCreateMessageRepository(gormDB)
	postController := controller.NewPostController(createMessageRepository)
	postHandler := handler.NewPostHandler(postController)
	engine := router.NewRouter(getHandler, postHandler)
	return engine
}
