// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller/getMessageController.go
//
// Generated by this command:
//
//	mockgen -source ./controller/getMessageController.go -destination=mocks/mock_getMessageController.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "ameato/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetMessageControllerInterface is a mock of GetMessageControllerInterface interface.
type MockGetMessageControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGetMessageControllerInterfaceMockRecorder
	isgomock struct{}
}

// MockGetMessageControllerInterfaceMockRecorder is the mock recorder for MockGetMessageControllerInterface.
type MockGetMessageControllerInterfaceMockRecorder struct {
	mock *MockGetMessageControllerInterface
}

// NewMockGetMessageControllerInterface creates a new mock instance.
func NewMockGetMessageControllerInterface(ctrl *gomock.Controller) *MockGetMessageControllerInterface {
	mock := &MockGetMessageControllerInterface{ctrl: ctrl}
	mock.recorder = &MockGetMessageControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMessageControllerInterface) EXPECT() *MockGetMessageControllerInterfaceMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockGetMessageControllerInterface) GetMessages(ctx context.Context) ([]model.MessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx)
	ret0, _ := ret[0].([]model.MessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockGetMessageControllerInterfaceMockRecorder) GetMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockGetMessageControllerInterface)(nil).GetMessages), ctx)
}
