// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller/getController.go
//
// Generated by this command:
//
//	mockgen -source ./controller/getController.go -destination=mocks/mock_getContoller.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "ameato/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetControllerInterface is a mock of GetControllerInterface interface.
type MockGetControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGetControllerInterfaceMockRecorder
	isgomock struct{}
}

// MockGetControllerInterfaceMockRecorder is the mock recorder for MockGetControllerInterface.
type MockGetControllerInterfaceMockRecorder struct {
	mock *MockGetControllerInterface
}

// NewMockGetControllerInterface creates a new mock instance.
func NewMockGetControllerInterface(ctrl *gomock.Controller) *MockGetControllerInterface {
	mock := &MockGetControllerInterface{ctrl: ctrl}
	mock.recorder = &MockGetControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetControllerInterface) EXPECT() *MockGetControllerInterfaceMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockGetControllerInterface) GetMessages(ctx context.Context) ([]model.MessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx)
	ret0, _ := ret[0].([]model.MessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockGetControllerInterfaceMockRecorder) GetMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockGetControllerInterface)(nil).GetMessages), ctx)
}
