// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/createMessage.go
//
// Generated by this command:
//
//	mockgen -source ./repository/createMessage.go -destination=mocks/mock_createMessage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "ameato/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateMessageRepositoryInterface is a mock of CreateMessageRepositoryInterface interface.
type MockCreateMessageRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreateMessageRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCreateMessageRepositoryInterfaceMockRecorder is the mock recorder for MockCreateMessageRepositoryInterface.
type MockCreateMessageRepositoryInterfaceMockRecorder struct {
	mock *MockCreateMessageRepositoryInterface
}

// NewMockCreateMessageRepositoryInterface creates a new mock instance.
func NewMockCreateMessageRepositoryInterface(ctrl *gomock.Controller) *MockCreateMessageRepositoryInterface {
	mock := &MockCreateMessageRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCreateMessageRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateMessageRepositoryInterface) EXPECT() *MockCreateMessageRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockCreateMessageRepositoryInterface) CreateMessage(ctx context.Context, message model.CreateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockCreateMessageRepositoryInterfaceMockRecorder) CreateMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockCreateMessageRepositoryInterface)(nil).CreateMessage), ctx, message)
}
