// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller/createMessageController.go
//
// Generated by this command:
//
//	mockgen -source ./controller/createMessageController.go -destination=mocks/mock_createMessageController.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "ameato/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateMessageControllerInterface is a mock of CreateMessageControllerInterface interface.
type MockCreateMessageControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreateMessageControllerInterfaceMockRecorder
	isgomock struct{}
}

// MockCreateMessageControllerInterfaceMockRecorder is the mock recorder for MockCreateMessageControllerInterface.
type MockCreateMessageControllerInterfaceMockRecorder struct {
	mock *MockCreateMessageControllerInterface
}

// NewMockCreateMessageControllerInterface creates a new mock instance.
func NewMockCreateMessageControllerInterface(ctrl *gomock.Controller) *MockCreateMessageControllerInterface {
	mock := &MockCreateMessageControllerInterface{ctrl: ctrl}
	mock.recorder = &MockCreateMessageControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateMessageControllerInterface) EXPECT() *MockCreateMessageControllerInterfaceMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockCreateMessageControllerInterface) CreateMessage(ctx context.Context, message model.CreateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockCreateMessageControllerInterfaceMockRecorder) CreateMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockCreateMessageControllerInterface)(nil).CreateMessage), ctx, message)
}
