// Code generated by MockGen. DO NOT EDIT.
// Source: ./controller/postController.go
//
// Generated by this command:
//
//	mockgen -source ./controller/postController.go -destination=mocks/mock_postContoller.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "ameato/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostControllerInterface is a mock of PostControllerInterface interface.
type MockPostControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostControllerInterfaceMockRecorder
	isgomock struct{}
}

// MockPostControllerInterfaceMockRecorder is the mock recorder for MockPostControllerInterface.
type MockPostControllerInterfaceMockRecorder struct {
	mock *MockPostControllerInterface
}

// NewMockPostControllerInterface creates a new mock instance.
func NewMockPostControllerInterface(ctrl *gomock.Controller) *MockPostControllerInterface {
	mock := &MockPostControllerInterface{ctrl: ctrl}
	mock.recorder = &MockPostControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostControllerInterface) EXPECT() *MockPostControllerInterfaceMockRecorder {
	return m.recorder
}

// PostMessages mocks base method.
func (m *MockPostControllerInterface) PostMessages(ctx context.Context, message model.CreateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMessages", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostMessages indicates an expected call of PostMessages.
func (mr *MockPostControllerInterfaceMockRecorder) PostMessages(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessages", reflect.TypeOf((*MockPostControllerInterface)(nil).PostMessages), ctx, message)
}
