// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/getMessage.go
//
// Generated by this command:
//
//	mockgen -source ./repository/getMessage.go -destination=mocks/mock_getMessage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "ameato/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetMessageRepositoryInterface is a mock of GetMessageRepositoryInterface interface.
type MockGetMessageRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGetMessageRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockGetMessageRepositoryInterfaceMockRecorder is the mock recorder for MockGetMessageRepositoryInterface.
type MockGetMessageRepositoryInterfaceMockRecorder struct {
	mock *MockGetMessageRepositoryInterface
}

// NewMockGetMessageRepositoryInterface creates a new mock instance.
func NewMockGetMessageRepositoryInterface(ctrl *gomock.Controller) *MockGetMessageRepositoryInterface {
	mock := &MockGetMessageRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockGetMessageRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetMessageRepositoryInterface) EXPECT() *MockGetMessageRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockGetMessageRepositoryInterface) GetMessages(ctx context.Context) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockGetMessageRepositoryInterfaceMockRecorder) GetMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockGetMessageRepositoryInterface)(nil).GetMessages), ctx)
}
