/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 表示可能なメッセージを取得する
         * @description 表示可能なメッセージを取得します。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.MessagesResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * メッセージを投稿する
         * @description メッセージを投稿します。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Message to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["model.CreateMessage"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.CreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "model.CreateMessage": {
            content: string;
            position: components["schemas"]["model.Position"];
        };
        "model.CreatedResponse": {
            message: components["schemas"]["model.MessageResponse"];
        };
        "model.ErrorResponse": {
            error?: string;
        };
        "model.MessageResponse": {
            content: string;
            opacity: number;
            position: components["schemas"]["model.Position"];
        };
        "model.MessagesResponse": {
            messages: components["schemas"]["model.MessageResponse"][];
        };
        "model.Position": {
            x: number;
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
